# there is no reason to use this makefile manually

.PHONY: build

ifeq (,$(PLATFORM))
$(error please specify PLATFORM, eg. make PLATFORM=minime)
endif

HOST_WORKSPACE=$(shell pwd)/workspace
GUEST_WORKSPACE=/root/workspace

DOCKER_DIR=toolchains/$(PLATFORM)-toolchain

all:
	docker run -it --rm -v $(HOST_WORKSPACE):$(GUEST_WORKSPACE) $(PLATFORM)-toolchain /bin/bash

build:
	docker run -it --rm -v $(HOST_WORKSPACE):$(GUEST_WORKSPACE) $(PLATFORM)-toolchain /bin/bash -c '. ~/.bashrc && cd /root/workspace && make'

image:
	docker build -t $(PLATFORM)-toolchain $(DOCKER_DIR)

clean:
